# Generated by Django 4.0.5 on 2022-12-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yoga_Class_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('session', models.CharField(max_length=100)),
                ('fee', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Yoga_Class_Data',
                'verbose_name_plural': 'Yoga_Class_Datas',
            },
        ),
    ]
