# Generated by Django 4.0.5 on 2022-12-10 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoneyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga_class_data',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
