# Generated by Django 4.0.5 on 2022-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoneyApp', '0002_yoga_class_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga_class_data',
            name='fullName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
