# Generated by Django 4.0.5 on 2022-12-11 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexmoneyApp', '0003_yoga_class_data_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga_class_data',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
